### PR TITLE
Improve edit error handling

### PR DESCRIPTION
**Pull request by APerson241**
If there's an error while editing, the API won't give us an 'edit' key in the response, so we shouldn't assume the presence of one.

### CODE REVIEW

**Comment by elifoster** [comment]
I would prefer we actually raise an error rather than returning error strings.

**Comment by APerson241** [comment]
Sure. How many error types are we going to make, then? There are a very
large number of possible errors with editing, and I'd prefer to cover them
with only the "EditError" type or something.

**Comment by elifoster** [comment]
IIRC many of MediaWiki's errors are duplicated across the actions, so we may be able to get away with doing something similar to the authentication errors. I'll compile a list of all of the errors (aside from the auth ones because we already support those) when I get a chance. For now I will leave this open. We could also support as many errors as possible and do something like what I did for the Cleverbot API and add an "UnsupportedError" type: https://github.com/CleverbotIO/ruby-cleverbot.io/blob/master/lib/cleverbot.rb#L59-L62 which indicates a potential bug in the library.

**Comment by elifoster** [comment]
Thank you for this :smile_cat:

**Pull request merged**
